### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by Bicco** [nosajio/Sketch-Modular-Scale#1]
Can you explain how do I install this plugin into Sketch?

**Comment by nosajio** [comment]
@Bicco I'm really sorry that I've only just seen this!

To make installation really easy there's now a packaged version of the plugin under Releases. Just download the file there, uncompress it, and then double click on the .sketchplugin file to install 😃

📦[Here's a link to the download](https://github.com/nosajio/Sketch-Modular-Scale/releases)
